### ISSUE TITLE
[last modified] date of  each feed

### ISSUE THREAD

**Issue by ed-g** [ed-g/gtfs-feed-archive#20]
> - GTFS Archive Tool needs to run automatically on a regular basis
> - We need for agency name, feed name, feed URL, and last modified date
>   to be available either in a CSV or from an API

Capturing a note.

I think the ZIP file download system is clunky for purposes except truly making an archive.

What we want is a way to query the historical versions of feeds contained in the archive and download their data via REST.

How about an endpoint that gives:
- Feed name
- Last modification-time
- Last check time
- Link to gtfs-api, which will give you the feed version there, provided the import is up to date
- Download link to feed directly from gtfs-archive. I suggest this since URL changes depending on which version we're talking about, and there's no guarantee older download URLs will work.

**Comment by aaronantrim** [comment]
This sounds perfect. We will want to show information just for the collection of Oregon feeds on oregon-gtfs.com.

**Comment by ed-g** [comment]
How about I prepare a NTE quote.
