### ISSUE TITLE
oregon-gtfs.com error

### ISSUE THREAD

**Issue by ehowington** [ed-g/gtfs-feed-archive#23]
this link is published on oregon-gtfs.com
http://archive.oregon-gtfs.com/oregon-public-feeds/archive-creator

it yields an error message

cc @ed-g 

spotted by ODOT

**Comment by ed-g** [comment]
Thanks, restarted.

@arr0nax would you add an uptime robot for this?

**Comment by arr0nax** [comment]
@ed-g yup, on it

**Comment by arr0nax** [comment]
created!
https://uptimerobot.com/dashboard#787415619

**Comment by ed-g** [comment]
@evantrillium per https://github.com/Trillium-Solutions/GTFSManager/issues/5295#issue-723540514 ODOT is no longer paying maintenance on this server. Is this still the case?

Clayton and I are in the process of rebuilding the archive system and the "old" server will go away unless we have a current maintenance need with them.

cc @NomeQ

**Comment by NomeQ** [comment]
The only thing I remember needing it for was (a) GTFS-API and (b) I recall some workflow with Greyhound that we discussed last fall that used it. I don't think we need it at all for ODOT, so if both those needs are taken care of, should be fine.

@christrillium may have context on the Greyhound project if you don't @ed-g -- I definitely don't!

**Comment by ed-g** [comment]
Ok thanks!

@christrillium can you tell me more about the greyhound workflow? We're rewriting GTFS-Archive and only want to implement features that are needed for the future.

**Comment by christrillium** [comment]
@ed-g Oh man I wish I knew. I will just ask Matthew and Sarah if they need it.

**Comment by christrillium** [comment]
@ed-g  Actually after reading this better. Don't worry about it. Do what you gotta do.

**Comment by trilliumtransit** [comment]
They'll still have options.

The existing gtfs-feed-archive software is open source, and the new version will be as well. If they decide they need it again we can either make modifications to the new version (which I'm calling gtfs-feed-archive-2 for the time being) or figure out a maintenance plan for the old version depending on which is less effort overall. Almost certainly the new version will be easier to work with, but both options exist.

Ed

**Comment by christrillium** [comment]
cool cool thanks Ed
